### ISSUE TITLE
Suggestion of command cmake

### ISSUE THREAD

**Issue by YangLi069** [Forec/monitor-recorder#1]
Your material in Shiyanlou is excellent for me to learn OpenCV.
When I tried to execute command "sudo make", there exists an error indicating "../../lib/libopencv_highgui.so.2.4.13：undefined to ‘TIFFReadRGBAStrip@LIBTIFF_4.0". 
That is a shortage of "-D BUILD_TIFF=ON" of command cmake. 
Setup: opencv2.4.13 ubuntu14.04.

**Comment by Forec** [comment]
感谢告知，请问 ubuntu 14.04 下 cmake 加上该参数后能否安装成功？

**Comment by YangLi069** [comment]
yes

**Comment by Forec** [comment]
感谢！已添加到 README 中。
